version: '3.8'

services:

  mysql_dev:
    container_name: mysql_dev
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=watch
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend_dev
    depends_on:
      mysql_dev:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DATABASE_URL=mysql://root:root@mysql_dev:3306/watch
      - FRONTEND_URL=http://localhost:3001
      - API_URL=http://localhost:3000
      - SECRET=motdepassesecret

  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    environment:
      - API_URL=http://localhost:3000

volumes:
  mysql:
